jobs:
- template: azure-pipelines-template.yml
  parameters:
    name: macOS
    vmImage: macOS-10.14

- template: azure-pipelines-template.yml
  parameters:
    name: Linux
    vmImage: ubuntu-18.04

- template: azure-pipelines-template.yml
  parameters:
   name: Windows
   vmImage: windows-2019
