[workspace]
resolver = "2"
members = [
  "crates/*",
  "packages/transformers/js/core",
  "packages/utils/node-resolver-rs",
  "packages/utils/dev-dep-resolver"
]

[patch.crates-io]
browserslist-rs = { git = "https://github.com/devongovett/browserslist-rs.git", branch = "wasm" }
