[package]
authors = ["Devon Govett <devongovett@gmail.com>"]
name = "parcel-image"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = "1"
napi-derive = "1"
oxipng = "5.0.0"
mozjpeg-sys = "1.0.0"
libc = "0.2"

[build-dependencies]
napi-build = "1"
