[package]
authors = ["Devon Govett <devongovett@gmail.com>"]
name = "parcel-resolver"
version = "0.1.0"
edition = "2021"

[dependencies]
xxhash-rust = { version = "0.8.10", features = ["xxh3"] }
url = "2.5.0"
percent-encoding = "2.3.1"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
bitflags = "1.3.2"
indexmap = { version = "1.9.3", features = ["serde"] }
itertools = "0.12.1"
json_comments = { path = "../../../crates/json-comments-rs" }
typed-arena = "2.0.2"
elsa = "1.10.0"
once_cell = "1.19.0"
glob-match = "0.2.1"
dashmap = "5.5.3"

[dev-dependencies]
assert_fs = "1.1.1"

[target.'cfg(windows)'.dev-dependencies]
is_elevated = "0.1.2"
