[package]
authors = ["Devon Govett <devongovett@gmail.com>"]
name = "parcel-resolver"
version = "0.1.0"
edition = "2021"

[dependencies]
napi = "2.3.3"
napi-derive = "2"
xxhash-rust = { version = "0.8.2", features = ["xxh3"] }
url = "*"
percent-encoding = "*"
serde = { version = "1.0.123", features = ["derive"] }
serde_json = "*"
es-module-lexer = { path = "/Users/devongovett/dev/es-module-lexer" }
bitflags = "*"
indexmap = { version = "*", features = ["serde"] }
itertools = "*"
json_comments = { git = "https://github.com/devongovett/json-comments-rs", branch = "strip_in_place" }
typed-arena = "*"
elsa = "*"
once_cell = "*"

[dev-dependencies]
criterion = "0.4.0"
glob = "*"
globset = "*"

[build-dependencies]
napi-build = "1"

[[bench]]
name = "glob"
harness = false
