[package]
name = "parcel"
version = "0.1.0"
edition = "2021"
description = "Parcel Bundler"

[lib]
path = "./src/lib.rs"

[dependencies]
parcel_core = { path = "../parcel_core" }
parcel_filesystem = { path = "../parcel_filesystem" }
parcel_package_manager = { path = "../parcel_package_manager" }
