[package]
authors = ["Devon Govett <devongovett@gmail.com>"]
name = "parcel-fs-search"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = "2.12.0"
napi-derive = "2.12.0"

[build-dependencies]
napi-build = "2"
