name: Continuous Integration

on:
  merge_group:
  pull_request:
  push:
    branches:
      - v2
      - molejniczak/asset-graph-request-tests

permissions:
  contents: read

jobs:
  unit_tests:
    name: Unit tests (${{ matrix.os }}, Node ${{ matrix.node }})
    strategy:
      matrix:
        node: [20]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: yarn
          node-version: ${{ matrix.node }}
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: ${{ matrix.os }}
      - name: Bump max inotify watches (Linux only)
        if: ${{ runner.os == 'Linux' }}
        run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p;
      - run: yarn --frozen-lockfile
      - run: yarn build-native-release
      - run: yarn test:unit
      - name: Upload @parcel/rust artifacts on Linux with Node v20
        if: ${{ runner.os == 'Linux' && matrix.node == 20 }}
        uses: actions/upload-artifact@v3
        with:
          name: Rust Linux Binaries
          path: |
            packages/core/rust/index.d.ts
            packages/core/rust/index.js
            packages/core/rust/*.node
