on: pull_request

name: Generate benchmarks

jobs:
  prBenchmarks:
    name: PR Benchmarks
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -leo pipefail {0}
    steps:
      - name: PR Benchmarks
        uses: Magi-KS/parcel-benchmark-action@fix-github-action-benchmark
        env:
          PARCEL_BENCHMARK_APIKEY: ${{ secrets.PARCEL_BENCHMARK_APIKEY }}
